version: '3'

services:
  db:
    image: mariadb:10.10
    ports:
      - '${DB_PORT}:3306'
    environment:
      MARIADB_DATABASE: "${DB_DATABASE}"
      MARIADB_ROOT_PASSWORD: "${DB_PASSWORD}"
    volumes:
      - bitdevelopment-db-data:/var/lib/mysql

volumes:
  bitdevelopment-db-data:
