query BaseQuery($locale: I18NLocaleCode, $filters: PageFiltersInput) {
  menu(locale: $locale) {
    ...MenuFrament
  }
  pages(filters: $filters, locale: $locale) {
    data {
      id
      attributes {
        cover {
          data {
            attributes {
              height
              alternativeText
              caption
              name
              url
              width
            }
          }
        }
        title
        page {
          ... on Error {
            code
            message
          }
          ... on ComponentPageParagraph {
            id
            title
            content
          }
          ... on ComponentPageImage {
            id
            title
            alt
            image {
              data {
                attributes {
                  alternativeText
                  caption
                  height
                  width
                  url
                }
              }
            }
          }
        }
      }
    }
  }
}