fragment MenuFrament on MenuEntityResponse {
    data {
        attributes {
            pages {
                data {
                    id
                    attributes {
                    slug
                    title
                    }
                }
            }
        }
    }
}